version: "3.8"

services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_URL: postgres://postgres:secret@localhost:5432/smart-vision-api-postgres
      POSTGRES_DB: smart-vision-api-postgres
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
